default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_USERNAME"] %>
  host: <%= ENV["DB_HOST"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  port: <%= ENV["DB_PORT"] %>

development:
  <<: *default
  database: Scheduled_Tweets_development

test:
  <<: *default
  database: Scheduled_Tweets_test

production:
  <<: *default
  database: Scheduled_Tweets_production
  username: Scheduled_Tweets
  password: <%= ENV["SCHEDULED_TWEETS_DATABASE_PASSWORD"] %>
